### ISSUE TITLE
v2.0.0beta issues

### ISSUE THREAD

**Issue by Govinda-Fichtner** [UnitedIncome/serverless-python-requirements#10]
When I use v2.0.0beta instead of v1.2 I have the following issues:

```
$ pip --version
pip 1.5.6 from /builds/pod/sls-stacks/venv/local/lib/python2.7/site-packages (python 2.7)
$ sls deploy -s staging
Serverless: Installing required Python packages...
 
  Error --------------------------------------------------
 
     
Usage:   
  pip <command> [options]

no such option:
     --isolated
```

When I upgrade to pip 9.0.1 I still get the following error:
```
$ SLS_DEBUG=* sls deploy -s staging
Serverless: Installing required Python packages...
Serverless: Linking required Python packages...
 
  Error --------------------------------------------------
 
     EEXIST: file already exists, symlink '.requirements/tests'
     -> './tests'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: EEXIST: file already exists, symlink '.requirements/tests' -> './tests'
    at Object.fs.symlinkSync (fs.js:1019:18)
    at fse.readdirSync.map.file (/usr/local/lib/node_modules/serverless-python-requirements/index.js:83:13)
    at Array.map (native)
    at ServerlessPythonRequirements.linkRequirements (/usr/local/lib/node_modules/serverless-python-requirements/index.js:82:40)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:91:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.6.0
     Serverless Version: 1.6.1
 
ERROR: Build failed: exit code 1
```

With v1.2 everything works fine.

**Comment by dschep** [comment]
Yeah, i should document and add a check that a newish version of pip is required (the docker way automatically upgrades it, but I don't feel comfortable upgrading stuff on a users box).

The second error is because you have a library called `test` required and a dir in your service by the same name. I'll at least make the code catch the linking error and explain it, not sure what else to do with out requiring you to alter your code like in v1. It'll of course work if you use the zip method which does still require you to change your code.
