### ISSUE TITLE
Doensn't pick up Pipfile!

### ISSUE THREAD

**Issue by devxpy** [UnitedIncome/serverless-python-requirements#169]
```
⋊> ~/P/s3_to_db_pipline tree -I node_modules                                                                                          
.
├── handler.py
├── package.json
├── package-lock.json
├── serverless.yml
└── xml_to_json
    ├── Pipfile
    ├── Pipfile.lock
    └── xml_to_json.py

⋊> ~/P/s3_to_db_pipline sls -v                                                                                                        
1.26.1

`serverless-python-requirements@4.0.0`
```

```
package:
  individually: true

plugins:
  - serverless-python-requirements

functions:
  xml_to_json:
    handler: xml_to_json.lambda_handler
    module: xml_to_json
    events:
      - s3:
        bucket: xyz
        rules:
          - prefix: XML/
          - suffix: .xml
```
```
⋊> ~/P/s3_to_db_pipline sls deploy                                                                                                    
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, open 'xml_to_json/requirements.txt'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.11.1
     Serverless Version:     1.26.1
```

If i add 
```
custom:
  pythonRequirements:
    fileName: Pipfile 
```
then i get this

```
Serverless: Installing requirements of xml_to_json/Pipfile in .serverless/xml_to_json...
 
  Error --------------------------------------------------
 
  Invalid requirement: '[[source]]'
Traceback (most recent call last):
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/home/dev/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'[[source'"


 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.11.1
     Serverless Version:     1.26.1
 

```

**Comment by dschep** [comment]
Hmm. I suspect its a issue with Pipfiles and package individually. I don't think that's been tested.
