### ISSUE TITLE
Error: Unable to find good bind path format

### ISSUE THREAD

**Issue by lucasnp** [UnitedIncome/serverless-python-requirements#210]
This issue just started to happen to me when packaging package with docker: I couldn't find answer anywhere. Not sure if this is with serverless or this plugin.

Error: Unable to find good bind path format

    at getBindPath (C:\Users\taing\Desktop\projects\wm-tc\node_modules\serverless-python-requirements\lib\docker.js:109:9)
    at installRequirements (C:\Users\taing\Desktop\projects\wm-tc\node_modules\serverless-python-requirements\lib\pip.js:92:22)
    at values.filter.map.f (C:\Users\taing\Desktop\projects\wm-tc\node_modules\serverless-python-requirements\lib\pip.js:226:11)
    at Array.map (<anonymous>)
    at ServerlessPythonRequirements.installAllRequirements (C:\Users\taing\Desktop\projects\wm-tc\node_modules\serverless-python-requirements\lib\pip.js:221:8)
From previous event:
    at PluginManager.invoke (C:\Users\taing\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:372:22)
    at PluginManager.run (C:\Users\taing\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:403:17)
    at variables.populateService.then (C:\Users\taing\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:102:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (C:\Users\taing\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:89:74)
    at serverless.init.then (C:\Users\taing\AppData\Roaming\npm\node_modules\serverless\bin\serverless:42:50)

**Comment by dschep** [comment]
cc @kichik

**Comment by kichik** [comment]
Please include the following information:
* Version of `serverless-python-requirements` used
* Output of `docker version`
* Output of `docker run --rm -v c:/Users/taing:/test busybox ls -lah /test`
* Output of `docker run --rm -v /c/Users/taing:/test busybox ls -lah /test`
* Any recent changes you've made. Did this start after a version upgrade? Docker upgrade? Windows update?

**Comment by lucasnp** [comment]
I did have windows update recently but not sure about docker.

I did update serverless-python-requirements recently as well. But not sure if it's related.

4.1.0

docker version:
`Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false`

`docker run --rm -v c:/Users/taing:/test busybox ls -lah /test
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
07a152489297: Pull complete
Digest: sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
Status: Downloaded newer image for busybox:latest
total 4
drwxr-xr-x    3 root     root          60 Jun 20 21:13 .
drwxr-xr-x    1 root     root        4.0K Jun 20 21:17 ..
drwxr-xr-x    3 root     root          60 Jun 20 21:13 Desktop`

`total 4
drwxr-xr-x    3 root     root          60 Jun 20 21:13 .
drwxr-xr-x    1 root     root        4.0K Jun 20 21:17 ..
drwxr-xr-x    3 root     root          60 Jun 20 21:13 Desktop`

**Comment by kichik** [comment]
That's weird. Everything seems in place. What version did you use before this? Also, please paste the output of:

    docker run --rm -v c:/Users/taing/Desktop/projects/wm-tc:/test alpine ls /test/serverless.yml

If you want to help debugging this, `lib/pip.js` line 40 could have some debug prints. Specifically you can print `ps.stdout` and if any exception is caught. That's the part that seems to be failing for you.

**Comment by illagrenan** [comment]
I had the same problem after clean installation of `serverless ` and `serverless-python-requirements`.

How i fixed this:

1. Open Docker for Windows
2. Go to Shared Drives
3. Make sure `C` is shared. If `C` is already shared, un-share it and share it again

**Comment by kichik** [comment]
@mrpgraae I've created a PR for that #213.
@illagrenan that should already be covered by the documentation, but it would be nice to detect it and print a good error message. That said, I don't think that's what @lucasnp had because they were able to confirm file sharing is working.

**Comment by mrpgraae** [comment]
@kichik 
That was fast!
Thank you for the nice plugin btw. Works great, now that I got around the filename issue 😄

**Comment by dschep** [comment]
Closed by #213 

@mrpgraae (should've asked before i merged, oh well). could you test this? install this plugin with 

```
npm i UniteIncome/serverless-python-requirements
```

**Comment by ajshukury** [comment]
I have the same issue. The filename is not an issue in my end. What else could go wrong to get this error?

**Comment by AndrewFarley** [comment]
Hey Windows-ey guys and other contributors.  I was looking at this getBindPath function, and recently used it in my PR and found it... a bit lacking.  It currently just searches through a list of files we expect to be there, shouldn't this function be modified to CREATE a file at the start of it which it then can test mounting in Docker, and then delete that file afterwards?  It seems a bit... silly, to have to check all the different possible files, and it's limited to only a folder that contains serverless repos, not _any_ folder, as it should be imho.  I almost made this modification in #165 but decided against it for now.  I'd love some thoughts/input/feedback before I just go and do it, wouldn't that be smarter?

**Comment by kichik** [comment]
I prefer not changing things when possible. You don't always have permissions, sometimes you crash and leave things behind, and in this case there should always be a file we know.

**Comment by AndrewFarley** [comment]
@kichik If you don't have permissions, then you won't be able to use this plugin, as it writes to the .serverless folder.  So, I strongly disagree.  :P

**Comment by kichik** [comment]
That specific part was a general comment. But it might apply to this plugin in the future. Someone might ask for a feature where the build folder is different than the source folder. It's a common request that helps make cleaner CI systems.

I am not following why you had to add `requirements.txt` to the list. Are you using the helper for something new? I haven't looked at your code.

**Comment by AndrewFarley** [comment]
So, that is EXACTLY what my MR does, already.  The MR does caching and building of pip requirements in a folder other than your serverless folder, which I needed for two reasons, one for CI/CD systems, and #2: for caching the output (static cache) from pip.  It no longer mounts your entire project path into Docker unnecessarily for building requirements, it uses an AppDir folder from your user/system/home/temp/vars, and/or you can specify a path.  This concept, however, falls apart with your current implementation of getBindPath because that only currently supports a serverless directory.

**Comment by kichik** [comment]
Makes sense to change it to a file it creates then, especially since you already had to do that anyway.

**Comment by AndrewFarley** [comment]
Thanks, I'll clean up the function in my MR then for your review, and maybe it'll help some of these other getBindPath issues (using the different folder may help, not the temp file thing)

**Comment by ajshukury** [comment]
Sounds good. I will do that. Thanks @kichik

**Comment by akuckreja** [comment]
Hey  @illagrenan , thanks, this worked for me!!!
i suspect this was required for me as my windows password had changed. So when i enabled sharing again, i had to put in my new password.

thanks again

> 
> 
> I had the same problem after clean installation of `serverless ` and `serverless-python-requirements`.
> 
> How i fixed this:
> 
>     1. Open Docker for Windows
> 
>     2. Go to Shared Drives
> 
>     3. Make sure `C` is shared. If `C` is already shared, un-share it and share it again

**Comment by krashmi** [comment]
Hello I am getting an error " Unable to find good bind path format " at the last step "serverless deploy". Using windows container in dockers on windows 10 os.
If I switch to Linux container I get a different error "
Error --------------------------------------------------
docker: Error response from daemon: invalid mode: /test.
See 'docker run --help'.
Please help

**Comment by moneerrifai** [comment]
I wrestled with this for a couple of days. This thread was super helpful. What finally resolved the issue for me was changing the way I was logged in to Docker: I was logged in using my email and password, which it turns out is a valid method to authenticate, but it causes an error when you try to pull down the docker image (which causes the bind path error). Instead, I had to log out and log as docker username/password (instead of docker user email / password) and it worked!

**Comment by krashmi** [comment]
Finally, my error below was resolved. 
 Unable to find good bind path format " at the last step "serverless deploy". Using windows container in dockers on windows 10 os.
If I switch to linux container I get a different error "

I used linux container on windows 10 ,  In addition to npm install --save serverless-python-requirements
i used fix **npm i T-Tmnr/serverless-python-requirements#fix-issue-274**  and deployment was successful.

**Comment by mojimi** [comment]
I fixed by typing :
```bash
docker login
```

And logging in, I couldn't login through the docker UI

**Comment by jorwoods** [comment]
I had the same issue. Was caused by docker running windows containers. Switching them to back to linux containers fixed the issue.

**Comment by adir1661** [comment]
had the same issue...
on windows at a linux command line like git bash i used:
    winpty docker login

**Comment by dhulke** [comment]
I fixed by turning docker desktop on

**Comment by Tsingis** [comment]
Getting this error when trying to use serverless framework and deploy AWS lambda via Github action and using windows-latest.

```
Serverless: Generated requirements from D:\a\telegram-bot\telegram-bot\requirements.txt in D:\a\telegram-bot\telegram-bot\.serverless\requirements.txt...
Serverless: Installing requirements from C:\Users\runneradmin\AppData\Local\UnitedIncome\serverless-python-requirements\Cache\5e61405b67ffec41db1bbd78f432bc4fd4ccdf0af1764200fd7a3859b7126a39_slspyc\requirements.txt ...
Serverless: Docker Image: lambci/lambda:build-python3.8
 
  Error --------------------------------------------------
 
  Error: Unable to find good bind path format
      at getBindPath (D:\a\telegram-bot\telegram-bot\node_modules\serverless-python-requirements\lib\docker.js:152:9)
      at installRequirements (D:\a\telegram-bot\telegram-bot\node_modules\serverless-python-requirements\lib\pip.js:198:39)
      at installRequirementsIfNeeded (D:\a\telegram-bot\telegram-bot\node_modules\serverless-python-requirements\lib\pip.js:556:3)
      at ServerlessPythonRequirements.installAllRequirements (D:\a\telegram-bot\telegram-bot\node_modules\serverless-python-requirements\lib\pip.js:635:29)
      at ServerlessPythonRequirements.tryCatcher (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\a\telegram-bot\telegram-bot\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by movaid7** [comment]
I fixed it by installing the latest version of Docker - 20.10.2

**Comment by dpeters1** [comment]
I found this error also pops up if you're operating in a different docker context. `docker context use default` resolved it for me.
