### ISSUE TITLE
unlink causes conflicts with serverless-wsgi

### ISSUE THREAD

**Issue by gmeans** [UnitedIncome/serverless-python-requirements#22]
I'm using the `dockerizePip` option and kept running into the following error when attempting to deploy:

```
  Error --------------------------------------------------
 
     ENOENT: no such file or directory, scandir '.requirements'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, scandir '.requirements'
    at Object.fs.readdirSync (fs.js:870:18)
    at ServerlessPythonRequirements.unlinkRequirements (/Users/grantmeans/Development/orlando-gun-club/range-manager/src/server/node_modules/serverless-python-requirements/index.js:100:11)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)

```

It looks like `unlinkRequirements` is called after `cleanup`. I'm able to run `sls requirements install` successfully, but `sls requirements clean` fails.

**Comment by gmeans** [comment]
Sorry I forgot to put environment info:

```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.2.1
     Serverless Version: 1.11.0
```

**Comment by gmeans** [comment]
turns out this was a plugin order issue. I'm using this with `serverless-wsgi` and that plugin needs to come after `serverless-python-requirements` since they both attempt to delete the `.requirements` folder.

```
plugins:
  - serverless-python-requirements
  - serverless-wsgi
```

Might be worth a comment in the readme. Thanks!

**Comment by dschep** [comment]
Ah. If you're using `serverless-wsgi` [you don't actually need this plugin](https://github.com/logandk/serverless-wsgi#automatic-requirement-packaging). I actually forked this from than because we weren't adapting WSGI code and at the time it didn't have a "package only" option. (and since then i've simplified (IMO) my logic and we need the docker I added support for deploying numpy from a Mac.

Tho, looking at that plugin again, It does seem that using both allows you not to have to add `.requirements` to your `sys.path`.

**Comment by gmeans** [comment]
Thanks @dschep . I chose to use both because my app uses c-compiled extensions (psycopg2) and assumed your docker process is the only one that would build that correctly.

Does `serverless-wsgi` do the same thing?

**Comment by dschep** [comment]
Ah. Good reason to use this plugin. `serverless-wsgi` does not have a process (docker or otherwise) for dealing with compiled libraries when not running an x86_64 Linux box.

**Comment by dschep** [comment]
One more thing: that section I linked mentions an option to turn off `sererless-wsgi`'s requirements bundling, you might wanna give that a shot.

**Comment by gmeans** [comment]
yeah I have that turned off and everything deploying successfully. But now I'm having import errors when deployed for a package that behaves fine locally :/.

Do you think there would be value to tracking that as an issue on this repo? In case it's a deployment use-case?

**Comment by dschep** [comment]
Sure. I'll leave this as open for visibility.

**Comment by gmeans** [comment]
I'm having an issue w/ a single package for my project. Here's the stack trace:

```
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/task/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/var/task/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/var/task/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/var/task/django/urls/base.py", line 158, in is_valid_path
    resolve(path, urlconf)
  File "/var/task/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/var/task/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/var/task/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/task/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/task/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/task/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/task/rangemanager/urls.py", line 18, in <module>
    from rest_framework_swagger.views import get_swagger_view
  File "/var/task/rest_framework_swagger/views.py", line 8, in <module>
    from . import renderers
  File "/var/task/rest_framework_swagger/renderers.py", line 1, in <module>
    import coreapi
  File "/var/task/coreapi/__init__.py", line 2, in <module>
    from coreapi import auth, codecs, exceptions, transports, utils
  File "/var/task/coreapi/auth.py", line 1, in <module>
    from coreapi.utils import domain_matches
  File "/var/task/coreapi/utils.py", line 1, in <module>
    from coreapi import exceptions
ImportError: cannot import name exceptions
```
I've verified that the coreapi package is in the deployment package and the exceptions module is there, but for some reason I get that ImportError. All other packages appear to be importing fine as when I remove the code that imports this the error disappears and I can reach the app.

This project does run fine locally. Posting this here in case this might be due to packaging.

**Comment by miketheman** [comment]
Closing, as this appears to be resolved via the wsgi plugin releasing https://github.com/logandk/serverless-wsgi/pull/25
