### ISSUE TITLE
Connection broken by SSLError

### ISSUE THREAD

**Issue by tainguyen206** [UnitedIncome/serverless-python-requirements#267]
Hi,

I am able to use the plugin on my home machine. However, running sls package at my work machine (Win10) return this error:

```
Collecting numpy==1.14.5 (from -r /var/task/requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)': /packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))
```

It seems like some proxy / certificate issues. I am not familiar with linux or networking so not so sure how to get around it.  I specified the proxies server in docker setting with no luck. 

Has anyone seen similar issue?

**Comment by dschep** [comment]
have you tried setting the `http_proxy` or `https_proxy` environment variables?

**Comment by dschep** [comment]
oh. you're using docker. the plugin would have to pass those through :thinking:

**Comment by lucasnp** [comment]
Thanks @dschep. I did added http(s)_proxy variables to my local machine. But I am not sure how to pass those along with the plugin. Is there some obvious option that i missed? :-s

**Comment by dschep** [comment]
Nope. No obvious solution. I'm unsure how I want to approach this. I see 3 options:
 * Pass `http_proxy` & `https_proxy` env vars (any other vars that might be interesting to pass if we're hard coding some?)
 * Pass all env vars
 * add an option to specify which env vars are passed. EG in your case:
```yaml
custom:
  pythonRequirements:
     dockerizePip: true
     dockerEnvVars:
       - http_proxy
       - https_proxy
```

**Comment by bsamuel-ui** [comment]
The quick answer is [configuring it in docker](https://docs.docker.com/network/proxy/) but we're looking at how the plugin might handle this more gracefully.

**Comment by lucasnp** [comment]
Thanks @bsamuel-ui , i made the change per your suggestion and it seems to work 👍 I got some errors but probably from other configuration. I will test it out more.

Thanks!

**Comment by dschep** [comment]
Just realized that we've already got #231 which is the 2nd option I mentioned. Cleaned it up and opening a PR for you to tests.

**Comment by tainguyen206** [comment]
@dschep , this is a bit silly. But how do I test it? :( where do i specify the env variables?

**Comment by dschep** [comment]
You don't have to specify any vars or options. Install the branch as I indicated in #271 and it should work. It passes ALL the environment variables to docker

**Comment by tainguyen206** [comment]
I got this error after installing the branch:

```
Type Error ---------------------------------------------

  options.dockerEnv.forEach is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: options.dockerEnv.forEach is not a function
    at installRequirements (C:\projects\wm-tc\node_modules\serverless-python-requirements\lib\pip.js:201:25)
    at installRequirementsIfNeeded (C:\projects\wm-tc\node_modules\serverless-python-requirements\lib\pip.js:457:3)
    at ServerlessPythonRequirements.installAllRequirements (C:\projects\wm-tc\node_modules\serverless-python-requirements\lib\pip.js:536:29)
From previous event:
    at PluginManager.invoke (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\nguyta\AppData\Roaming\npm\node_modules\serverless\bin\serverless:43:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.12.0
     Serverless Version:     1.32.0
```
