### ISSUE TITLE
Error: no such option: --keep-outdated

### ISSUE THREAD

**Issue by lindy64** [UnitedIncome/serverless-python-requirements#277]
Hello,

I am trying to upload a vanilla serverless python Lambda, just using the following steps:

`npm install -g serverless`
`serverless create --template aws-python3 --name test-lambda`
`pipenv shell`
`pipenv install requests`
`pipenv lock`
`sls plugin install -n serverless-python-requirements`

All this seems to work fine, but when I do a `sls deploy --stage dev` I am getting the following error:

`Error: no such option: --keep-outdated`

The debug output is:

`  at ServerlessPythonRequirements.pipfileToRequirements (/Users/myuser/projects/guardduty/node_modules/serverless-python-requirements/lib/pipenv.js:34:11)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:50`

environment:

`System Version: macOS 10.14.1 (18B75)`
`Python 3.6.1`
`sls verion 1.32.0`

I am sure it is something stupid I am doing, but any suggestions would be appreciated!

Thanks! :-)

**Comment by dschep** [comment]
You probably need to update your pipenv version. `pip install -U pipenv`

**Comment by lindy64** [comment]
Thanks dschep, just did that, but same error unfortunatley.. I am now on `pipenv, version 9.0.1`

**Comment by dschep** [comment]
That's still an old version of pipenv: https://pypi.org/project/pipenv/#history

**Comment by lindy64** [comment]
sorry, should have checked that..

updated with brew, rather than pip and all working fine now...thank you for the swift response! :-)
