### ISSUE TITLE
dockerEnv - Environment variable not available in container

### ISSUE THREAD

**Issue by rockycore** [UnitedIncome/serverless-python-requirements#298]
Hi folks,

we are using SLS and python requirements to packjage our python handler. 
Besides we are integrating the distribution of a private repository by using token to access the repo content.
For this we are setting the token with an environment variable and use the dockerEnv to transfer the variable to the docker container.
Unfortunately the variable is not set when we try to access it in our setup.py file during packaging.
Besides the environment variable is available within sls (`${env:GITHUB_TOKEN} `) 
and it works fine without dockerizing (`dockerizePip: false`)
Any help here appreciated. Thanks. 

OS:                     	 	darwin
Node Version:           		9.4.0
Serverless Version:     		1.29.2
python-requirements Version: 	4.2.5

serverless.yaml:
```
pythonRequirements:
    dockerizePip: true
    pipCmdExtraArgs:
      - '--process-dependency-links'
    dockerEnv:
      - GITHUB_TOKEN
```
 
setup.py:
```
import os
from setuptools import setup, find_packages

github_token = os.getenv('GITHUB_TOKEN', None)

setup(
    version='0.0.1',
    name='my-lib',
    author='XXXXXX',
    author_email='XXXXXX',
    description='XXXXXX',
    long_description='XXXXXX,
    url='XXXXXX',
    packages=find_packages(where="./src"),
    package_data={
        'yoma.util': ['data.csv']
    },
    package_dir={"": "src"},
    zip_safe=True,
    keywords="",
    classifiers=[
        'Development Status :: 1 - Planning',
        'Programming Language :: Python :: 3.6',
    ],
    dependency_links=[
        f"git+https://{github_token}@github.com/user/my-lib.git@v0.1.0#egg=my-lib-v0.1.0"
    ],
    install_requires=[
        'boto3==1.7.14',
        'my-lib==0.1.0'
    ]
)
```   
    
Error message:
```
  Stack Trace --------------------------------------------
 
Error: DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release. A possible replacement is PEP 508 URL dependencies. You can find discussion regarding this at https://github.com/pypa/pip/issues/4187.
Command "git clone -q https://None@github.com/user/my-lib.git /tmp/pip-install-51su5snj/my-lib" failed with error code 128 in None

    at installRequirements (/Users/xxx/devspace/xxx/xxx/node_modules/serverless-python-requirements/lib/pip.js:146:11)
    at ServerlessPythonRequirements.installAllRequirements (/Users/xxx/devspace/xxx/xxx/node_modules/serverless-python-requirements/lib/pip.js:242:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>
```

**Comment by dschep** [comment]
Did you figure out what was wrong @rockycore ?
