### ISSUE TITLE
Serverless plugin "serverless-python-requirements" initialization errored: Unexpected token {

### ISSUE THREAD

**Issue by dtenenba** [UnitedIncome/serverless-python-requirements#363]
This is my first time using serverless and since I normally use pipenv, I installed this plugin since it should handle reading my dependencies from my Pipfile.

The first time I tried to deploy my function, I got this:

```

$ sls deploy
  Serverless Error ---------------------------------------

  Serverless plugin "serverless-python-requirements" initialization errored: Unexpected token {

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           4.3.0
     Serverless Version:     1.42.3
```

Where is the `{` that it is complaining about?
There are no syntax errors in my handler (it's just basically a hello world handler that imports a few third-party requirements; I can invoke it with `sls invoke local` .
There are no `{` characters in my handler or in serverless.yml.
There are some in Pipfile.lock but that doesn't seem to be the problem. As an experiment I renamed that file to something else and got the same error.

handler.py:

```python

import elasticsearch
import scrapy
import sh


import json


def hello(event, context):
    out = sh.ls("-lR", "/opt")
    txt = out.stdout.decode("utf-8")
    body = {
        "message": "Go Serverless v1.0! Your function executed successfully!",
        "log": txt,
        "input": event
    }

    response = {
        "statusCode": 200,
        "body": json.dumps(body)
    }

    return response

```

serverless.yml:

```yaml
service: wiki-reindexer-lambda # NOTE: update this with your service name


provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
  region: us-west-2

functions:
  hello:
    handler: handler.hello
 

plugins:
  - serverless-python-requirements

```

package.json:

```json
{
  "name": "wiki-reindexer-lambda",
  "description": "",
  "version": "0.1.0",
  "dependencies": {},
  "devDependencies": {
    "serverless-python-requirements": "^4.3.0"
  }
}
```

If I comment out the `plugins` section of serverless.yml the deployment succeeds, but `sls invoke` fails because it can't find the imports at the top of the handler. 

BTW, if it's relevant, I don't seem to have a `.serverless` directory in my project directory. Not sure if that matters but I saw it mentioned [here](https://dzone.com/articles/serverless-and-virtualenv-unable-to-import-module) and [here](https://www.npmjs.com/package/serverless-python-requirements). Not sure how or when that gets created.

If you are interested in the stack trace, I ran with SLS_DEBUG set to generate it:

```
  Stack Trace --------------------------------------------

SyntaxError: Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:100:24
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:98:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:151:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:94:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:72:26
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:70:8)
    at /usr/local/lib/node_modules/serverless/bin/serverless:42:21
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by dtenenba** [comment]
OK, googled the error, saw an earlier issue saying I needed to upgrade node. Did that and this error went away, but I got a new error (that `pipenv lock` has no option `--keep-outdated`. Updated pipenv and that went away.

So closing the isue.
