### ISSUE TITLE
Cannot set property 'pythonRequirements' of undefined

### ISSUE THREAD

**Issue by petergaultney** [UnitedIncome/serverless-python-requirements#374]
I am probably just misunderstanding how layers are supposed to work.

I have 
```
functions:
  getWorkflow:
    handler: vision_workflow.api.AS_LAM_getWorkflow
    memorySize: 1024
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

custom:
  pythonRequirements:
    layer: true
    slim: true
    useDownloadCache: true
    noDeploy: []
```

and I get this: 

```
Serverless: Packaging Python Requirements Lambda Layer...

  Type Error ---------------------------------------------

  Cannot set property 'pythonRequirements' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot set property 'pythonRequirements' of undefined
    at ServerlessPythonRequirements.createLayers (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless-python-requirements/lib/layer.js:28:56)
From previous event:
    at ServerlessPythonRequirements.layerRequirements (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless-python-requirements/lib/layer.js:57:6)
From previous event:
    at Object.after [as hook] (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless-python-requirements/index.js:181:10)
    at BbPromise.reduce (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.spawn (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/classes/PluginManager.js:409:17)
    at Deploy.BbPromise.bind.then (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/peter/workspace/vision-nx-aws/vision-nx-workflow/node_modules/serverless/bin/serverless:44:28)
    at <anonymous>
```

**Comment by petergaultney** [comment]
This had to do with not having Serverless >= 1.34 installed. The documentation should be updated to note the new version required.
