### ISSUE TITLE
Poetry

### ISSUE THREAD

**Issue by khornberg** [UnitedIncome/serverless-python-requirements#400]
This is related to #324 
When I have a `pyproject.toml` file I must explicitly say `usePoetry: false` to package the requirements.

In the current versions of things I get `ENOENT: no such file or directory, open '/Users/kyle/projects/serverless-python-requirements-bug/.serverless/requirements.txt'`

The above error results from falling into https://github.com/UnitedIncome/serverless-python-requirements/blob/c9d910cc40d95163f8894abfdefaf9c4fc33b505/lib/pip.js#L66 

Whatever the logic is to determine if `usePoetry` is true seems to be at fault.

A working example is at https://github.com/khornberg/serverless-python-requirements-bug

- Clone and run `sls package` to get the error
- Uncomment the `custom` section in the `serverless.yaml` file. Running `sls package` again works.

There is a work around but it seems unintuitive

**Comment by dschep** [comment]
What version of the plugin are you using?

**Comment by khornberg** [comment]
serverless-python-requirements@5.0.0

**Comment by Lewuathe** [comment]
I faced the same problem with 5.0.0. As @khornberg suggested, setting `usePoetry: false` resolved the issue.

**Comment by bsamuel-ui** [comment]
I haven't directly confirmed this, but we're seeing multiple reports with the same remedy.

**Comment by revmischa** [comment]
I *am* using poetry and see this issue, 5.1.0
```
  Error: ENOENT: no such file or directory, open '/Users/cyber/dev/project/.serverless/requirements.txt'
      at Object.openSync (fs.js:439:3)
      at Object.readFileSync (fs.js:344:35)
      at getRequirements (/Users/cyber/dev/project/node_modules/serverless-python-requirements/lib/pip.js:354:6)
      at filterRequirementsFile (/Users/cyber/dev/project/node_modules/serverless-python-requirements/lib/pip.js:381:24)
      at generateRequirementsFile (/Users/cyber/dev/project/node_modules/serverless-python-requirements/lib/pip.js:67:5)
      at installRequirementsIfNeeded (/Users/cyber/dev/project/node_modules/serverless-python-requirements/lib/pip.js:501:3)
```
