### ISSUE TITLE
Deploying Python serverless app fails with nonsensical/incomplete error message

### ISSUE THREAD

**Issue by skytreader** [UnitedIncome/serverless-python-requirements#439]
See also serverless/serverless#7084.

I'm deploying a Python app in serverless and I get a Buffer object for a failure message:

```
 Exception -----------------------------------------------
 
  <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 68 6f 6d 65 2f 63 ... >
 ```

This is all I get even with the verbose flag set or with `SLS_DEBUG=*`.

If you translate the hexdump you will see that it's the beginning of a Python stack trace:

```
Traceback (most recent call last):
  File "/home/c
```

Ideally, I'd want to see the whole stack trace.

**Comment by skytreader** [comment]
I updated `serverless-python-requirements` and the error became a bit more verbose but no more enlightening (at least for me):

```
Serverless: Packaging required Python packages...
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/serverless_project/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/serverless_project/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/serverless_project/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/serverless_project/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'FetchError',
  message:
   'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }

/serverless_project/node_modules/serverless/lib/classes/Error.js:94
    throw new Error(inspect(e));
          ^
Error: <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 68 6f 6d 65 2f 63 ... >
    at process.module.exports.logError.e (/serverless_project/node_modules/serverless/lib/classes/Error.js:94:11)
    at process.emit (events.js:198:13)
    at process.emit (/serverless_project/node_modules/source-map-support/source-map-support.js:465:21)
    at /serverless_project/node_modules/bluebird/js/release/debuggability.js:199:33
    at activeFireEvent (/serverless_project/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/serverless_project/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/serverless_project/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/serverless_project/node_modules/bluebird/js/release/debuggability.js:44:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by skytreader** [comment]
Following the discussion at serverless/serverless#6454 I disabled serverless stats but unfortunately it seems to be unrelated to my problem. I'm now just basically back at square one:

```
Serverless: Packaging required Python packages...

/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/serverless/lib/classes/Error.js:94
    throw new Error(inspect(e));
          ^
Error: <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 68 6f 6d 65 2f 63 ... >
    at process.module.exports.logError.e (/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/serverless/lib/classes/Error.js:94:11)
    at process.emit (events.js:198:13)
    at process.emit (/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/source-map-support/source-map-support.js:465:21)
    at /home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/bluebird/js/release/debuggability.js:199:33
    at activeFireEvent (/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/home/cestioco/kode/goodgame/lmt-pubsub-cache/node_modules/bluebird/js/release/debuggability.js:44:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by bsamuel-ui** [comment]
Please generate a minimal test case to help reproduce this. It should contain these items:

* package.json
* lockfile
* serverless.yml
* requirements / pipenv file
* a stub handler file

**Comment by gliptak** [comment]
https://github.com/logandk/serverless-wsgi/issues/122
