### ISSUE TITLE
ENOENT: no such file or directory, open '.serverless/requirements.txt'

### ISSUE THREAD

**Issue by mar-io** [UnitedIncome/serverless-python-requirements#45]
I am trying to run `sls deploy` from a docker container and I am having issues with the plugin looking within the `.serverless` file for the requirements.txt. I am not sure what is wrong with my environment as in the past it did work as expected.

The problem is `sls deploy` deletes the .serverless folder so looking in the directory is pointless. Any ideas why this may be occuring?

```
bash-4.2# sls deploy
Serverless: Parsing Python requirements.txt
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, open '.serverless/requirements.txt'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, open '.serverless/requirements.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at ServerlessPythonRequirements.parseRequirements (/serverless/metrics/email_notification_runner_metrics/node_modules/serverless-python-requirements/index.js:63:9)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:229:17)
    at Deploy.BbPromise.bind.then.then (/usr/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:101:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:99:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:32:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.1
     Serverless Version:     1.17.0
```

**Comment by dschep** [comment]
I just released v2.4.0 which parses `requirements.txt` and filters out some lines and writes it back to `.serverless/requirements.txt`. I always had that dir around and our CI was happy when I deployed it so thanks for pointing this out since i wouldn't have found it, bugfix should be coming soon.
