### ISSUE TITLE
using different runtimes

### ISSUE THREAD

**Issue by Selion05** [UnitedIncome/serverless-python-requirements#512]
just got the same error as in #436

>     Error: nodejs12.x not found! Try the pythonBin option.
      at pipAcceptsSystem (/node_modules/serverless-python-requirements/lib/pip.js:100:13)
      at installRequirements (/node_modules/serverless-python-requirements/lib/pip.js:173:9)

I fixed it by removing the provider runtime (which was nodejs12.x)

Seems like the function runtime is ignored when a provider runtime is present?

**Comment by hansheng654** [comment]
had same problem... can't get webpack and python to work together
