### ISSUE TITLE
Error with `serverless-python-requirements` and AWS invokeLocal functionality

### ISSUE THREAD

**Issue by brooks-macbeth-shadowdragon** [UnitedIncome/serverless-python-requirements#543]
When running `$ sls invoke local -f hello --log --docker --stage local` I got the following output

```log
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Generating requirements.txt from Pipfile...
Serverless: Parsed requirements.txt from Pipfile in /path/to/project/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /Users/me/Library/Caches/serverless-python-requirements/698cb61ae5cba231b8c2fc7d8ea3a58580ce3127745beb871b77b9ceccc025a5_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...
 
    Type Error ---------------------------------------------
 
    TypeError: layer.split is not a function
            at /path/to/project/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:283:34
            at Array.map (<anonymous>)
            at AwsInvokeLocal.getLayerPaths (/path/to/project/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:262:90)
            at /path/to/project/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:437:16
            at tryCatcher (/path/to/project/node_modules/bluebird/js/release/util.js:16:23)
            at Promise._settlePromiseFromHandler (/path/to/project/node_modules/bluebird/js/release/promise.js:547:31)
            at Promise._settlePromise (/path/to/project/node_modules/bluebird/js/release/promise.js:604:18)
            at Promise._settlePromise0 (/path/to/project/node_modules/bluebird/js/release/promise.js:649:10)
            at Promise._settlePromises (/path/to/project/node_modules/bluebird/js/release/promise.js:729:18)
            at _drainQueueStep (/path/to/project/node_modules/bluebird/js/release/async.js:93:12)
            at _drainQueue (/path/to/project/node_modules/bluebird/js/release/async.js:86:9)
            at Async._drainQueues (/path/to/project/node_modules/bluebird/js/release/async.js:102:5)
            at Immediate.Async.drainQueues [as _onImmediate] (/path/to/project/node_modules/bluebird/js/release/async.js:15:14)
            at processImmediate (internal/timers.js:456:21)
            at process.topLevelDomainCallback (domain.js:137:15)
 
         For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
    Get Support --------------------------------------------
         Docs:          docs.serverless.com
         Bugs:          github.com/serverless/serverless/issues
         Issues:        forum.serverless.com
 
    Your Environment Information ---------------------------
         Operating System:          darwin
         Node Version:              14.4.0
         Framework Version:         1.82.0 (local)
         Plugin Version:            3.8.4
         SDK Version:               2.3.1
         Components Version:        2.34.9
```

After adding in some debugging statements I was able to narrow down what had happened. The `serverless-python-requirements` module has incorrectly packaged the `layer` object that they are returning. A workaround for this was added and the `invoke local` function worked as expected. Here is what the object looks like:

```jsonc
{
  ...,
  "PythonRequirementsLambdaLayer": {
    "artifact": ".serverless/pythonRequirements.zip",
    "name": "name-local-python-requirements",
    "description": "Python requirements generated by serverless-python-requirements.",
    "compatibleRuntimes": ["python3.8"],
    "package": {/*The `artifact` field should be here*/}
  }
}
```

PATCH:`serverless-python-requirements/lib/layer.js`
```javascript
/**
 * Creates a layer on the serverless service for the requirements zip.
 * @return {Promise} empty promise
 */
function createLayers() {
  if (!this.serverless.service.layers) {
    this.serverless.service.layers = {};
  }
  this.serverless.service.layers['pythonRequirements'] = Object.assign(
    {
      // Add `package` field to layer for proper processing in Serverless
      package: {
        artifact: path.join('.serverless', 'pythonRequirements.zip')
      },
      name: `${
        this.serverless.service.service
      }-${this.serverless.providers.aws.getStage()}-python-requirements`,
      description:
        'Python requirements generated by serverless-python-requirements.',
      compatibleRuntimes: [this.serverless.service.provider.runtime]
    },
    this.options.layer
  );

  return BbPromise.resolve();
}
```

After this patch running the top command yield:

```log
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Generating requirements.txt from Pipfile...
Serverless: Parsed requirements.txt from Pipfile in /path/to/project/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /Users/me/Library/Caches/serverless-python-requirements/698cb61ae5cba231b8c2fc7d8ea3a58580ce3127745beb871b77b9ceccc025a5_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...
Serverless: Unziping PythonRequirementsLambdaLayer...
START RequestId: b25e2481-be15-1937-d2bb-cddf44014155 Version: $LATEST
END RequestId: b25e2481-be15-1937-d2bb-cddf44014155
REPORT RequestId: b25e2481-be15-1937-d2bb-cddf44014155  Init Duration: 1704.10 ms       Duration: 113.30 ms     Billed Duration: 200 ms Memory Size: 1024 MB   Max Memory Used: 38 MB

{}
```

**Comment by bricelalu** [comment]
This is very good, thanks, I had the same issue and now it's working locally, do you think @brooks-macbeth-shadowdragon you can create a pull request or at least a branch?

Then I think I could reference it in my package.json before

**Comment by terrybondy** [comment]
I ran into this problem as well.
