### ISSUE TITLE
Tests won't run

### ISSUE THREAD

**Issue by winstonewert** [UnitedIncome/serverless-python-requirements#55]
I was trying to run the tests so I can pull a fix for my other issue. But I can't get the tests to run. When I do I get:

```

1..8
not ok 1 py3.6 can package requests with default options
# (in test file test.bats, line 20)
#   `sls package' failed
# npm WARN example@1.0.0 No description
# npm WARN example@1.0.0 No repository field.
# 
# + serverless-python-requirements@2.5.0
# added 44 packages in 11.518s
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
not ok 2 py3.6 can package requests with zip option
# (in test file test.bats, line 27)
#   `sls package' failed
# npm WARN example@1.0.0 No description
# npm WARN example@1.0.0 No repository field.
# 
# + serverless-python-requirements@2.5.0
# added 44 packages in 1.289s
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
ok 3 # skip (can't dockerize on linux if not root & not in docker group) py3.6 can package requests with zip & dockerizePip option
ok 4 # skip (can't dockerize on linux if not root & not in docker group) py3.6 can package requests with dockerizePip option
not ok 5 py2.7 can package requests with default options
# (in test file test.bats, line 52)
#   `sls package' failed
# npm WARN example@1.0.0 No description
# npm WARN example@1.0.0 No repository field.
# 
# + serverless-python-requirements@2.5.0
# added 44 packages in 1.291s
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
not ok 6 py2.7 can package requests with zip option
# (in test file test.bats, line 59)
#   `sls package' failed
# npm WARN example@1.0.0 No description
# npm WARN example@1.0.0 No repository field.
# 
# + serverless-python-requirements@2.5.0
# added 44 packages in 1.387s
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
#  
#   Serverless Error ---------------------------------------
#  
#   Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#  
#   Stack Trace --------------------------------------------
#  
# ServerlessError: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
#     at plugins.forEach (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:81:17)
#     at Array.forEach (native)
#     at PluginManager.loadPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
#     at PluginManager.loadServicePlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
#     at PluginManager.loadAllPlugins (/home/winstonewert/n/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
#     at service.load.then (/home/winstonewert/n/lib/node_modules/serverless/lib/Serverless.js:64:28)
#     at <anonymous>
# From previous event:
#     at runCallback (timers.js:781:20)
#     at tryOnImmediate (timers.js:743:5)
#     at processImmediate [as _immediateCallback] (timers.js:714:5)
# From previous event:
#     at __dirname (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:25:46)
#     at Object.<anonymous> (/home/winstonewert/n/lib/node_modules/serverless/bin/serverless:43:4)
#     at Module._compile (module.js:569:30)
#     at Object.Module._extensions..js (module.js:580:10)
#     at Module.load (module.js:503:32)
#     at tryModuleLoad (module.js:466:12)
#     at Function.Module._load (module.js:458:3)
#     at Function.Module.runMain (module.js:605:10)
#     at startup (bootstrap_node.js:158:16)
#     at bootstrap_node.js:575:3
#  
#   Get Support --------------------------------------------
#      Docs:          docs.serverless.com
#      Bugs:          github.com/serverless/serverless/issues
#      Forums:        forum.serverless.com
#      Chat:          gitter.im/serverless/serverless
#  
#   Your Environment Information -----------------------------
#      OS:                     linux
#      Node Version:           8.2.1
#      Serverless Version:     1.19.0
#  
ok 7 # skip (can't dockerize on linux if not root & not in docker group) py2.7 can package requests with zip & dockerizePip option
ok 8 # skip (can't dockerize on linux if not root & not in docker group) py2.7 can package requests with dockerizePip option

```

**Comment by dschep** [comment]
Hmm. That is odd. What happens if you `cd example && npm i ..` ? (that's what the 1st setup step of the tests do.

Feel free to push the branch and open a PR so our CircleCI will run the tests for you.

**Comment by winstonewert** [comment]
Ok, I figured out:

- You need serverless installed globally
- You also need to run npm install on the root of the repo, the test running npm install .. isn't sufficient.

**Comment by winstonewert** [comment]
I don't have a pull request to try, as the first thing I did was attempt to get the test running.

**Comment by dschep** [comment]
Yup. Definitely need sls installed globally, the later I didn't realize, I don't think it does in CI :man_shrugging:

**Comment by winstonewert** [comment]
I can see it running the npm install when I look at the CI logs, so that's explains that.

**Comment by dschep** [comment]
Oh, you're right, `circle.yml` does that before `bats` gets called.
