### ISSUE TITLE
Error while deploying serverless package: Error: STDOUT

### ISSUE THREAD

**Issue by skyblasy** [UnitedIncome/serverless-python-requirements#562]
Hi all,

So I've been using serverless and this plugin for this past year without much issue. I had taken a bit of a break from it, and went back to a project yesterday and attempted to do a deploy and got an unexpected error. 

```
 Error --------------------------------------------------

  Error: STDOUT:

  STDERR: Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
      at C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\serverless-python-requirements\lib\pip.js:325:13
      at Array.forEach (<anonymous>)
      at installRequirements (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\serverless-python-requirements\lib\pip.js:312:28)
      at installRequirementsIfNeeded (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\serverless-python-requirements\lib\pip.js:556:3)
      at ServerlessPythonRequirements.installAllRequirements (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\serverless-python-requirements\lib\pip.js:635:29)
      at ServerlessPythonRequirements.tryCatcher (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\schuy\Documents\data_science\Proficio\Serverless\process-v5\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

I assure you, I have python installed. I believe I installed the plugin correctly too, and I'm not sure what else has changed since I used it last about 3 weeks ago or so when I didn't have any issues.

I went to serverless support first, and the technician/assistant referred me to here for assistance since he said it was an issue with the plugin. 

To be fair, this is the first time I attempted to deploy this particular project, but everything prior to about 3 weeks/a month ago worked fine, so this is a bit of a surprise. 

Any ideas on what's going on or how to resolve this? 

Thank you,
Schuyler

**Comment by skyblasy** [comment]
Actually figured out what was going on. I had a file for python requirements (numpy, pandas, datetime), and for this project i wanted to use the SES SDK, and tried packaging email (to make use of MIMEtext but email was not a valid package), but email is not valid. 

Does anyone why that is not being packaged or how to get that dependency as part of m stack?

**Comment by dtosato** [comment]
I reported a similar issue (#563) yesterday. I have no idea about how to solve it, but I think it depends on the last update of `pip`.
