### ISSUE TITLE
use this in combination with serverless lambda docker functionality

### ISSUE THREAD

**Issue by araker** [UnitedIncome/serverless-python-requirements#612]
Hello, 

In my  project I'm using functions that are built using a docker container, using the [build in serverless functionality](https://www.serverless.com/blog/container-support-for-lambda), but I also want to create non docker functions with the serverless-python-requirements plugin. The serverless-python-requirements tries to create a zip for each function, which is something I want to prevent for the docker container ones. Is there a way to exclude a function from the functionality from this plugin or turn the plugin off for a function? 

My docker function definition looks like this
![Capture_provider](https://user-images.githubusercontent.com/430230/121585577-0753b000-ca33-11eb-8ac5-3fe60b135bf3.PNG)

![Capture_function](https://user-images.githubusercontent.com/430230/121585574-06bb1980-ca33-11eb-8cc0-e59529089a15.PNG)

**Comment by araker** [comment]
And then you realize that the 'plugin' and 'custom' keyword can also be added to the function and aren't top level keywords only.

**Comment by divyeshramani** [comment]
I have tried this too and couldn't find any way to ignore python-requirements module or specify requirements file when deploying a lambda with ecr image.  Please provide a fix, it would be greatly appreciated.

**Comment by davehemming** [comment]
I've just run into this issue myself, I would also like this plugin to ignore certain function definitions in the serverless file.

**Comment by pgrzesik** [comment]
Hey @araker - could you please post the output/error that you're getting when running `deploy/package`?

**Comment by davehemming** [comment]
If it's helpful, when I include a lambda container function in the serverless.yml file that also has the plugin declared I get the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
      at readFile (fs.js:343:10)
      at go$readFile (/home/ubuntu/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:118:14)
      at readFile (/home/ubuntu/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:115:12)
      at go$readFile (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/graceful-fs/graceful-fs.js:118:14)
      at Object.readFile (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/graceful-fs/graceful-fs.js:115:12)
      at Object.readFile (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/universalify/index.js:5:57)
      at Object.tryCatcher (/home/ubuntu/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/home/ubuntu/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
      at injectRequirements (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/serverless-python-requirements/lib/inject.js:23:6)
      at /home/ubuntu/tmp/jw-met-proj-sls/node_modules/serverless-python-requirements/lib/inject.js:128:13
      at tryCatcher (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/util.js:16:23)
      at MappingPromiseArray._promiseFulfilled (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/map.js:68:38)
      at MappingPromiseArray.PromiseArray._iterate (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise_array.js:115:31)
      at MappingPromiseArray.init (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise_array.js:79:10)
      at Promise._settlePromise (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:601:21)
      at Promise._settlePromise0 (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:673:18)
      at MappingPromiseArray.PromiseArray._resolve (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise_array.js:127:19)
      at MappingPromiseArray._promiseFulfilled (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/map.js:108:18)
      at Promise._settlePromise (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/tmp/jw-met-proj-sls/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:462:21)
```

**Comment by pgrzesik** [comment]
Thank you @davehemming :bow: For now the workaround is to dpeloy such functions as a separate stack, I'm also in the process of getting more familiar with the plugin and I'm hoping to find some time in the upcoming weeks to investigate bugs like this one.

**Comment by davehemming** [comment]
Thank you @pgrzesik, much appreciated.  This is the workaround that I'm using currently and it's working fine.

**Comment by hoang-innomizetech** [comment]
The latest master code seems fixed this issue but the published version is still old. Could we have a new version released?
