### ISSUE TITLE
Package fails when requirements.txt is a symlink to a file not in the service directory

### ISSUE THREAD

**Issue by dwolfand** [UnitedIncome/serverless-python-requirements#97]
Proposed fix - copy it to `.serverless/requirements.txt` just like we do when its a pipfile.

**Comment by dwolfand** [comment]
Still not working:

```
Running `serverless deploy` in dev with AWS_PROFILE=dev
Serverless: Installing required Python packages with python3.6...
Serverless: Docker Image: lambci/lambda:build-python3.6
 
  Error --------------------------------------------------
 
  Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.10.1
     Serverless Version:     1.19.0
 
Traceback (most recent call last):
  File "deploy.py", line 66, in <module>
    main()
  File "/Users/david/repos/ui-data-downgrade/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/repos/ui-data-downgrade/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/david/repos/ui-data-downgrade/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/repos/ui-data-downgrade/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "deploy.py", line 58, in main
    run_serverless(serverless, cwd='dev', profile_name='dev', dry_run=dry_run, verbose=verbose, force=force)
  File "deploy.py", line 41, in run_serverless
    check_call(cmd, cwd=cwd, env={'AWS_PROFILE': profile_name, 'PATH': os.getenv('PATH')})
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/david/repos/ui-data-downgrade/node_modules/.bin/serverless', 'deploy']' returned non-zero exit status 1.
```
